inherits = "kanagawa-dragon"

"ui.gutter" = { bg = "dragonBlack3" }
"ui.linenr" = { bg = "dragonBlack3" }

"ui.gutter.selected" = { bg = "dragonBlack4" }
"ui.linenr.selected" = { fg = "roninYellow", bg = "dragonBlack4", modifiers = ["bold"] }
"ui.cursorline.primary" = { bg = "dragonBlack4" }
"ui.cursorcolumn.primary" = { bg = "dragonBlack4" }
