[cursor.style]
blinking = "Off"
shape = "Block"

[font]
size = 12.0

[font.bold]
style = "Medium"

[font.bold_italic]
style = "Semibold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "None"
key = "N"
mods = "Super"

[[keyboard.bindings]]
action = "None"
key = "T"
mods = "Super"

[scrolling]
history = 10000

[terminal.shell]
program = "/opt/homebrew/bin/bash"

[window]
decorations = "buttonless"
dynamic_title = true
opacity = 0.95
blur = true
title = "Terminal"
option_as_alt = "Both"

[window.padding]
x = 4
y = 4

[general]
live_config_reload = true
working_directory = "None"
import = ["/Users/jerluc/.config/alacritty/themes/themes/kanagawa_wave.toml"]

[terminal]
