#!/usr/bin/env sh

# Unload the macOS WindowManager process
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

# Hide the dock
defaults write com.apple.dock autohide -bool true && killall Dock
defaults write com.apple.dock autohide-delay -float 1000 && killall Dock
defaults write com.apple.dock no-bouncing -bool TRUE && killall Dock

# Restores the dock
# defaults write com.apple.dock autohide -bool false && killall Dock
# defaults delete com.apple.dock autohide-delay && killall Dock
# defaults write com.apple.dock no-bouncing -bool FALSE && killall Dock

# TODO: First need to disable system integrity protection:
# https://github.com/koekeishiya/yabai/wiki/Disabling-System-Integrity-Protection
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa


yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

# yabai -m signal --add event=display_added action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
# yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
# $HOME/.config/yabai/create_spaces.sh

yabai -m config \
                window_border              on           \
                mouse_follows_focus        off          \
                focus_follows_mouse        on           \
                window_placement           second_child \
                window_topmost             on           \
                window_shadow              float        \
                window_opacity             on           \
                window_opacity_duration    0.15         \
                active_window_opacity      1.0          \
                normal_window_opacity      0.9          \
                window_border_width        1            \
                window_border_radius       10           \
                window_animation_duration  0.15         \
                active_window_border_color 0xffffddaa   \
                normal_window_border_color 0x00ffddaa   \
                insert_feedback_color      0xff9dd274   \
                split_ratio                0.50         \
                auto_balance               on           \
                mouse_modifier             fn           \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                                                        \
                top_padding                4            \
                bottom_padding             4            \
                left_padding               4            \
                right_padding              4            \
                window_gap                 4

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(Notes|Numbers|Pages|Reminders|Calendar|Weather|Preview|Font Book|System Information|Finder|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|QuickTime Player|Activity Monitor)$" manage=off
yabai -m rule --add app="^(Steam|Steam Helper|OBS Studio|Live|Midinous|Raycast|Meld|MacDown|1Password|VCV Rack 2 Free|8BitDo Firmware Updater|Microsoft Excel)$" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off

# Auto-space rules
yabai -m rule --add app="^Slack$" space=^3
yabai -m rule --add app="^Telegram$" space=^4

# Special exception for Slack screensharing
yabai -m rule --add app=^Slack$ subrole!=AXStandardWindow border=off
yabai -m rule --add app=^Slack$ title="Huddle" subrole=AXStandardWindow manage=off

# yabai -m config external_bar               all:20:0

yabai -m config layout bsp

echo "yabai configuration loaded.."
